// src/pages/Dashboard.jsx
import React from 'react';
import Logo from '../components/Logo';
import { Home, FileText, AlertTriangle, CheckCircle, Settings, User, Bell, Search, BarChart3 } from 'lucide-react';
import { BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';

export default function GenericlabDashboard() {

  const stats = [
    { label: 'CAPA Actives', value: '24', change: '+5 ce mois', icon: FileText },
    { label: 'En Attente', value: '8', change: '+2 ce mois', icon: FileText },
    { label: 'Clôturées', value: '142', change: '+12 ce mois', icon: CheckCircle },
    { label: 'Taux Efficacité', value: '94%', change: '+2% ce mois', icon: BarChart3 }
  ];


  // Données pour les graphiques
  const monthlyData = [
    { mois: 'Jan', actives: 18, clôturées: 15 },
    { mois: 'Fév', actives: 22, clôturées: 18 },
    { mois: 'Mar', actives: 20, clôturées: 22 },
    { mois: 'Avr', actives: 25, clôturées: 20 },
    { mois: 'Mai', actives: 28, clôturées: 24 },
    { mois: 'Juin', actives: 24, clôturées: 28 },
  ];

  const statusData = [
    { name: 'En cours', value: 24, color: '#3B82F6' },
    { name: 'En Attente', value: 8, color: '#F59E0B' },
    { name: 'Clôturées', value: 142, color: '#10B981' },
  ];

  const departmentData = [
    { departement: 'Production', nombre: 45 },
    { departement: 'Qualité', nombre: 38 },
    { departement: 'QA', nombre: 32 },
    { departement: 'Maintenance', nombre: 28 },
    { departement: 'Documentation', nombre: 20 },
  ];

  return (
    <div className="flex h-screen bg-gray-50">
      {/* Sidebar */}
      <aside className="w-64 bg-white border-r border-gray-200 flex flex-col">
        {/* Logo Genericlab */}
        <Logo />

        {/* Navigation */}
        <nav className="flex-1 py-6 px-4">
          <div className="mb-6">
            <button type="button" className="flex items-center space-x-3 px-4 py-3 rounded-xl" style={{ backgroundColor: '#E3F2FD', color: '#0066CC' }}>
              <Home className="w-5 h-5" />
              <span className="font-medium">Dashboard</span>
            </button>
          </div>

          <div className="space-y-1">
            <button type="button" className="flex items-center space-x-3 px-4 py-3 text-gray-600 hover:bg-gray-50 rounded-xl transition-colors">
              <FileText className="w-5 h-5" />
              <span className="font-medium">Tables</span>
            </button>
            <button type="button" className="flex items-center space-x-3 px-4 py-3 text-gray-600 hover:bg-gray-50 rounded-xl transition-colors">
              <AlertTriangle className="w-5 h-5" />
              <span className="font-medium">Déviations</span>
            </button>
            <button type="button" className="flex items-center space-x-3 px-4 py-3 text-gray-600 hover:bg-gray-50 rounded-xl transition-colors">
              <BarChart3 className="w-5 h-5" />
              <span className="font-medium">Rapports</span>
            </button>
          </div>

          <div className="mt-8 pt-6 border-t border-gray-200">
            <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-3 px-4">Account Pages</p>
            <div className="space-y-1">
              <button type="button" className="flex items-center space-x-3 px-4 py-3 text-gray-600 hover:bg-gray-50 rounded-xl transition-colors">
                <User className="w-5 h-5" />
                <span className="font-medium">Profile</span>
              </button>
              <button type="button" className="flex items-center space-x-3 px-4 py-3 text-gray-600 hover:bg-gray-50 rounded-xl transition-colors">
                <Settings className="w-5 h-5" />
                <span className="font-medium">Paramètres</span>
              </button>
            </div>
          </div>
        </nav>

        {/* Help Card - Style Purity UI */}
        <div className="mx-4 mb-6 p-5 rounded-2xl" style={{ background: 'linear-gradient(135deg, #4FC3F7 0%, #00BCD4 100%)' }}>
          <div className="w-12 h-12 bg-white bg-opacity-30 rounded-full flex items-center justify-center mb-3">
            <span className="text-2xl">❓</span>
          </div>
          <h3 className="text-white font-bold text-base mb-1">Besoin d'aide?</h3>
          <p className="text-white text-sm opacity-90 mb-4">Consultez notre documentation</p>
          <button className="w-full bg-white text-sm font-semibold py-2.5 px-4 rounded-xl transition-all hover:shadow-lg" style={{ color: '#00BCD4' }}>
            DOCUMENTATION
          </button>
        </div>
      </aside>

      {/* Main Content */}
      <div className="flex-1 flex flex-col overflow-hidden">
        {/* Top Navigation Bar */}
        <header className="h-20 bg-white border-b border-gray-100 flex items-center justify-between px-8">
          <div>
            <p className="text-sm text-gray-500 mb-1">Pages / Dashboard</p>
            <h2 className="text-xl font-bold text-gray-800">Dashboard</h2>
          </div>

          <div className="flex items-center space-x-4">
            <div className="relative">
              <input
                type="text"
                placeholder="Type here..."
                className="w-64 pl-10 pr-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:outline-none focus:border-gray-300 transition-colors"
              />
              <Search className="w-4 h-4 text-gray-400 absolute left-3.5 top-3.5" />
            </div>
            
            <button className="p-2.5 hover:bg-gray-50 rounded-xl transition-colors">
              <User className="w-5 h-5 text-gray-600" />
            </button>
            
            <button className="p-2.5 hover:bg-gray-50 rounded-xl transition-colors">
              <Settings className="w-5 h-5 text-gray-600" />
            </button>
            
            <button className="p-2.5 hover:bg-gray-50 rounded-xl transition-colors relative">
              <Bell className="w-5 h-5 text-gray-600" />
            </button>
            
            <button className="px-4 py-2.5 text-sm font-medium text-gray-700 hover:bg-gray-50 rounded-xl transition-colors flex items-center space-x-2">
              <span>Sign In</span>
            </button>
          </div>
        </header>

        {/* Main Content Area */}
        <main className="flex-1 overflow-y-auto p-8" style={{ backgroundColor: '#F8F9FA' }}>
          {/* Stats Cards */}
          <div className="grid grid-cols-4 gap-6 mb-8">
            {stats.map((stat, index) => (
              <div key={index} className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
                <div className="flex items-center justify-between mb-3">
                  <div className="w-14 h-14 rounded-2xl flex items-center justify-center" style={{ backgroundColor: index === 0 ? '#E3F2FD' : index === 1 ? '#FFF3E0' : index === 2 ? '#E8F5E9' : '#E0F7FA' }}>
                    <stat.icon className="w-7 h-7" style={{ color: index === 0 ? '#0066CC' : index === 1 ? '#FF9800' : index === 2 ? '#4CAF50' : '#00BCD4' }} />
                  </div>
                </div>
                <p className="text-sm text-gray-500 font-medium mb-1">{stat.label}</p>
                <p className="text-2xl font-bold text-gray-800 mb-1">{stat.value}</p>
                <p className="text-xs text-gray-400">{stat.change}</p>
              </div>
            ))}
          </div>

          {/* Graphiques et Analyses */}
          <div className="mt-8">
            <div className="mb-4">
              <h3 className="text-lg font-bold text-gray-800">Analyses et Statistiques</h3>
              <p className="text-sm text-gray-500">Vue d'ensemble des performances CAPA</p>
            </div>

            <div className="grid grid-cols-2 gap-6">
              {/* Graphique en barres - Évolution mensuelle */}
              <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
                <h4 className="font-bold text-gray-800 mb-4">Évolution Mensuelle</h4>
                <ResponsiveContainer width="100%" height={250}>
                  <BarChart data={monthlyData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#E5E7EB" />
                    <XAxis dataKey="mois" stroke="#6B7280" />
                    <YAxis stroke="#6B7280" />
                    <Tooltip />
                    <Legend />
                    <Bar dataKey="actives" fill="#0066CC" name="CAPA Actives" radius={[8, 8, 0, 0]} />
                    <Bar dataKey="clôturées" fill="#10B981" name="CAPA Clôturées" radius={[8, 8, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>

              {/* Graphique circulaire - Répartition par statut */}
              <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
                <h4 className="font-bold text-gray-800 mb-4">Répartition par Statut</h4>
                <ResponsiveContainer width="100%" height={250}>
                  <PieChart>
                    <Pie
                      data={statusData}
                      cx="50%"
                      cy="50%"
                      labelLine={false}
                      label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                      outerRadius={80}
                      fill="#8884d8"
                      dataKey="value"
                    >
                      {statusData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.color} />
                      ))}
                    </Pie>
                    <Tooltip />
                  </PieChart>
                </ResponsiveContainer>
              </div>

              {/* Graphique en barres horizontales - Par département */}
              <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100 col-span-2">
                <h4 className="font-bold text-gray-800 mb-4">CAPA par Département</h4>
                <ResponsiveContainer width="100%" height={250}>
                  <BarChart data={departmentData} layout="vertical">
                    <CartesianGrid strokeDasharray="3 3" stroke="#E5E7EB" />
                    <XAxis type="number" stroke="#6B7280" />
                    <YAxis dataKey="departement" type="category" stroke="#6B7280" />
                    <Tooltip />
                    <Bar dataKey="nombre" fill="#00BCD4" name="Nombre de CAPA" radius={[0, 8, 8, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>
          </div>

        </main>
      </div>
    </div>
  );
}

// stack_app/frontend/pages/dashboard.vue
<template>
  <div class="flex h-screen bg-gray-50">
    <Sidebar />

    <!-- Main Content -->
    <div class="flex-1 overflow-auto">
      <!-- Header -->
      <header class="bg-white border-b border-gray-200 px-8 py-4">
        <div class="flex items-center justify-between">
          <div>
            <h1 class="text-2xl font-bold text-gray-800">Dashboard</h1>
            <p class="text-gray-600">Vue d'ensemble de la gestion des CAPA</p>
          </div>
          <div class="flex items-center space-x-4">
            <button class="p-2 hover:bg-gray-100 rounded-lg relative">
              <Bell :size="20" class="text-gray-600" />
              <span class="absolute top-1 right-1 w-2 h-2 bg-red-500 rounded-full"></span>
            </button>
            <div class="flex items-center space-x-3">
              <div class="w-10 h-10 bg-blue-600 rounded-full flex items-center justify-center">
                <span class="text-white font-medium">{{ userInitials }}</span>
              </div>
            </div>
          </div>
        </div>
      </header>

      <!-- Content -->
      <main class="p-8">
        <!-- Stats Cards -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          <div
            v-for="(stat, index) in stats"
            :key="index"
            class="card"
          >
            <div class="flex items-center justify-between mb-4">
              <component :is="stat.icon" :size="24" class="text-blue-600" />
            </div>
            <p class="text-3xl font-bold text-gray-800 mb-1">{{ stat.value }}</p>
            <p class="text-sm text-gray-600 mb-2">{{ stat.label }}</p>
            <p class="text-xs text-green-600 font-medium">{{ stat.change }}</p>
          </div>
        </div>

        <!-- Charts Row -->
        <!-- Charts Row -->
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
          <!-- CAPA par Status -->
          <div class="card h-96 flex flex-col">
            <div class="flex items-center justify-between mb-2">
              <h3 class="text-lg font-bold text-gray-800">CAPA par Statut</h3>
              <button class="p-2 hover:bg-gray-50 rounded-lg text-gray-400 hover:text-gray-600">
                <BarChart3 :size="20" />
              </button>
            </div>
            <div class="flex-1 min-h-0 relative">
              <ClientOnly>
                <DoughnutChart v-if="chartDataStatus" :data="chartDataStatus" />
              </ClientOnly>
            </div>
          </div>

          <!-- CAPA par Département -->
          <div class="card h-96 flex flex-col">
            <div class="flex items-center justify-between mb-2">
              <h3 class="text-lg font-bold text-gray-800">CAPA par Département</h3>
              <button class="p-2 hover:bg-gray-50 rounded-lg text-gray-400 hover:text-gray-600">
                <FileText :size="20" />
              </button>
            </div>
            <div class="flex-1 min-h-0 relative">
              <ClientOnly>
                <BarChart v-if="chartDataDept" :data="chartDataDept" />
              </ClientOnly>
            </div>
          </div>
        </div>

        <!-- Recent CAPA Table -->
        <div class="card">
          <div class="flex items-center justify-between mb-6">
            <h3 class="text-lg font-bold text-gray-800">CAPA Récentes</h3>
            <NuxtLink to="/tables" class="text-sm text-blue-600 hover:text-blue-700 font-medium">
              Voir tout
            </NuxtLink>
          </div>

          <div class="overflow-x-auto" v-if="recentCAPAs.length > 0">
            <table class="w-full">
              <thead>
                <tr class="border-b border-gray-200">
                  <th class="text-left py-3 px-4 text-sm font-semibold text-gray-700">ID</th>
                  <th class="text-left py-3 px-4 text-sm font-semibold text-gray-700">Titre</th>
                  <th class="text-left py-3 px-4 text-sm font-semibold text-gray-700">Type</th>
                  <th class="text-left py-3 px-4 text-sm font-semibold text-gray-700">Statut</th>
                  <th class="text-left py-3 px-4 text-sm font-semibold text-gray-700">Priorité</th>
                  <th class="text-left py-3 px-4 text-sm font-semibold text-gray-700">Responsable</th>
                </tr>
              </thead>
              <tbody>
                <tr
                  v-for="capa in recentCAPAs"
                  :key="capa.id"
                  class="border-b border-gray-100 hover:bg-gray-50"
                >
                  <td class="py-3 px-4 text-sm text-gray-600">#{{ capa.id }}</td>
                  <td class="py-3 px-4 text-sm font-medium text-gray-800">{{ capa.titre }}</td>
                  <td class="py-3 px-4 text-sm text-gray-600">{{ capa.type }}</td>
                  <td class="py-3 px-4">
                    <span
                      class="px-2 py-1 text-xs font-medium rounded-full"
                      :class="getStatusClass(capa.statut)"
                    >
                      {{ capa.statut }}
                    </span>
                  </td>
                  <td class="py-3 px-4">
                    <span
                      class="px-2 py-1 text-xs font-medium rounded-full"
                      :class="getPriorityClass(capa.priorite)"
                    >
                      {{ capa.priorite }}
                    </span>
                  </td>
                  <td class="py-3 px-4 text-sm text-gray-600">{{ capa.responsable }}</td>
                </tr>
              </tbody>
            </table>
          </div>
          <div v-else class="text-center py-10 text-gray-400 bg-gray-50/50 rounded-lg border border-dashed border-gray-200">
            <p>Aucune CAPA récente</p>
          </div>
        </div>
      </main>
    </div>
  </div>
</template>

<script setup>
import { Bell, FileText, CheckCircle, AlertCircle, BarChart3 } from 'lucide-vue-next'
import DoughnutChart from '~/components/charts/DoughnutChart.vue'
import BarChart from '~/components/charts/BarChart.vue'

// Authentification temporairement désactivée pour tests
// definePageMeta({
//   middleware: 'auth'
// })

useHead({
  title: 'Dashboard'
})

const api = useApi()

const statsData = ref(null)
const recentCAPAs = ref([])
const loading = ref(true)

const stats = ref([
  { label: 'CAPA Actives', value: '0', change: '+0 ce mois', icon: FileText },
  { label: 'En Attente', value: '0', change: '+0 ce mois', icon: AlertCircle },
  { label: 'Clôturées', value: '0', change: '+0 ce mois', icon: CheckCircle },
  { label: 'Taux Efficacité', value: '0%', change: '+0% ce mois', icon: BarChart3 }
])

const statusData = ref([
  { name: 'En cours', value: 0, color: '#3B82F6' },
  { name: 'Ouverte', value: 0, color: '#F59E0B' },
  { name: 'Clôturée', value: 0, color: '#10B981' }
])

const departmentData = ref([
  { departement: 'Qualité', nombre: 0 },
  { departement: 'Production', nombre: 0 },
  { departement: 'Laboratoire', nombre: 0 },
  { departement: 'Maintenance', nombre: 0 }
])

const totalCAPAs = computed(() => statusData.value.reduce((sum, s) => sum + s.value, 0))
const maxDept = computed(() => Math.max(...departmentData.value.map(d => d.nombre)))

// Chart Data Computed Properties
const chartDataStatus = computed(() => {
  return {
    labels: statusData.value.map(s => s.name),
    datasets: [
      {
        backgroundColor: statusData.value.map(s => s.color),
        data: statusData.value.map(s => s.value),
        borderWidth: 0,
        hoverOffset: 4
      }
    ]
  }
})

const chartDataDept = computed(() => {
  const colors = ['#3B82F6', '#10B981', '#F59E0B', '#8B5CF6', '#EF4444', '#06B6D4', '#EC4899', '#14B8A6'];
  return {
    labels: departmentData.value.map(d => d.departement),
    datasets: [
      {
        label: 'Nombre de CAPA',
        backgroundColor: departmentData.value.map((_, index) => colors[index % colors.length]),
        borderRadius: 4,
        categoryPercentage: 1.0,
        barPercentage: 1.0,
        data: departmentData.value.map(d => d.nombre)
      }
    ]
  }
})

const userInitials = computed(() => {
  if (process.client) {
    const user = JSON.parse(localStorage.getItem('user') || '{}')
    return `${user.prenom?.[0] || ''}${user.nom?.[0] || ''}`.toUpperCase() || 'U'
  }
  return 'U'
})

const getStatusClass = (status) => {
  const classes = {
    'En cours': 'bg-blue-50 text-blue-700 border border-blue-200',
    'Ouverte': 'bg-amber-50 text-amber-700 border border-amber-200',
    'Clôturée': 'bg-emerald-50 text-emerald-700 border border-emerald-200'
  }
  return classes[status] || 'bg-gray-50 text-gray-700 border border-gray-200'
}

const getPriorityClass = (priority) => {
  const classes = {
    'Haute': 'bg-red-50 text-red-700 border border-red-200',
    'Moyenne': 'bg-orange-50 text-orange-700 border border-orange-200',
    'Basse': 'bg-blue-50 text-blue-700 border border-blue-200'
  }
  return classes[priority] || 'bg-gray-50 text-gray-700 border border-gray-200'
}

onMounted(async () => {
  try {
    // Charger les statistiques
    const response = await api.getDashboardStats()

    if (response.success) {
      const data = response.data

      // Mettre à jour les stats cards
      stats.value = [
        { label: 'CAPA Actives', value: data.stats.totalCapas.toString(), change: '+5 ce mois', icon: FileText },
        { label: 'En Attente', value: data.stats.ouvertes.toString(), change: '+2 ce mois', icon: AlertCircle },
        { label: 'Clôturées', value: data.stats.cloturees.toString(), change: '+12 ce mois', icon: CheckCircle },
        { label: 'Taux Efficacité', value: '94%', change: '+2% ce mois', icon: BarChart3 }
      ]

      // Mettre à jour statusData
      statusData.value = [
        { name: 'En cours', value: data.stats.enCours, color: '#3B82F6' },
        { name: 'Ouverte', value: data.stats.ouvertes, color: '#F59E0B' },
        { name: 'Clôturée', value: data.stats.cloturees, color: '#10B981' }
      ]

      // Mettre à jour departmentData
      if (data.capaParDepartement) {
        departmentData.value = data.capaParDepartement
      }

      // CAPA récentes
      recentCAPAs.value = data.capasRecentes || []
    }
  } catch (error) {
    console.error('Error loading dashboard:', error)
  } finally {
    loading.value = false
  }
})
</script>
